### ISSUE TITLE
General refactor / roadmap

### ISSUE THREAD

**Issue by Maticzpl** [Maticzpl/TPT-LuaAPI-Addon#22]
- [ ] Reorder functions in a way that makes more sense and is more consistent.
- [x] Split into multiple files according to how wiki pages are split
- [x] Move declarations of constant values to bottom of each API section
- [x] Move all `@alias` and `@enum` annotations to top of each API section below constants, review each of those and update if necessary
- [x] Add comments to declarations of each lua API category from wiki
- [ ] Once wiki formatting gets more consistant, automate the process of updating the declarations. Use the raw mediawiki source from each wiki page instead of already rendered html
